# This workflow sets up and runs MSBuild and VSTest
# to build and test a Visual Studio solution.

name: Build and Unit Test in Ubuntu

on:
  push:
    branches: 
      - main
      - development
  
  pull_request:
    branches:
      - main
      - development

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    name: Run MSBuild and VSTest
     
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK v3.1
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: '3.1.x'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Unit Test
        run: dotnet vstest
