# This workflow sets up and runs MSBuild and VSTest
# to build and test a Visual Studio solution.

name: Build and Unit Test with MS Visual C++ Unit Test Framework

on:
  push:
    branches: 
      - main
      - development
  
  pull_request:
    branches:
      - main
      - development

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    name: Run MSBuild and VSTest
     
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: configure
      run: ./configure
      
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck
