name: NuGet Restore
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    name: NuGet@latest sample
    steps:
      - uses: actions/checkout@master
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ matrix.nuget }}
      - run: nuget restore template_cpp.sln
